env:
  browser: true
  es6: true
extends: 
- 'eslint:recommended'
- 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  test: readonly
  expect: readonly
  describe: readonly
  it: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - react
rules:
  "react/jsx-uses-react": "error"
  "react/jsx-uses-vars": "error"
  no-console: "off"
